README.md

@mikehardy here is an answer from [your question](https://github.com/actions/virtual-environments/issues/2187#issuecomment-1122700339) about nested virtualization support. Unfortunately, it's not supported yet and you can't run something like Docker inside Tart VMs.

Two more FAQs

---

Sources/tart/VMDirectory+OCI.swift

Before pulling an image.
```console
tart pull ghcr.io/cirruslabs/macos-monterey-base:latest
pulling ghcr.io/cirruslabs/macos-monterey-base:latest...
pulling manifest...
pulling disk (18.1GB compressed)...
```

Print total size of compressed layers

---

README.md

Minor typo: 'reposiotry' > 'repository'

---

Sources/tart/Commands/Create.swift

To help with frustrations like https://github.com/cirruslabs/tart/issues/44#issuecomment-1126831261
Experts will still use `--disk-size` flag to tailor disk size for their needs.

Change default disk size upon creation

---

Sources/tart/VMStorageLocal.swift

Similarly to what's done in `VMStorageOCI`: https://github.com/cirruslabs/tart/blob/efc9c74b6c557862fad8f5d1316976d3f772eb33/Sources/tart/VMStorageOCI.swift#L45-L47
Resolves https://github.com/cirruslabs/tart/issues/75.

tart list: filter out uninitialized VM directories

---

.ci/set-version.sh
.goreleaser.yml
Sources/tart/CI/CI.swift
Sources/tart/Commands/Run.swift
Sources/tart/Root.swift

Some explainer on why we need to use things like `envsubst`:
* https://stackoverflow.com/questions/27804227/using-compiler-variables-in-swift
* https://medium.com/@lucianoalmeida1/continuous-integration-environment-variables-in-ios-projects-using-swift-f72e50176a91
Resolves https://github.com/cirruslabs/tart/issues/42.

Support "tart --version"

---

Sources/tart/VM.swift

To prevent frustrations like #84

Bump default CPU cores

---

Package.resolved
Package.swift
Sources/tart/Commands/Run.swift
Sources/tart/VM+Recovery.swift
Sources/tart/VM.swift

Fixes #25
@trodemaster pointed out that @saagarjha found out the private API to start a VM in recovery mode. I kindly looked at [`VirtualApple` implementation](https://github.com/saagarjha/VirtualApple/blob/c737f41dae24c40996ded7dccb222b160c857de8/VirtualApple/VirtualMachine.swift#L135-L145).

Option to run in recovery mode

---

Package.resolved
Package.swift
Sources/tart/Logging/ProgressObserver.swift
Sources/tart/OCI/Registry.swift
Sources/tart/VMDirectory+OCI.swift
Tests/TartTests/RegistryTests.swift

Should help with #41 
I've tested by pulling and pushing an image.

Async http client for pull/push

---

Sources/tart/Commands/Set.swift
Sources/tart/VM.swift
Sources/tart/VMConfig.swift

It appeared there is a hand `(for screen: NSScreen, sizeInPoints: NSSize)` constructor of `VZMacGraphicsDisplayConfiguration` which does the configuration for us. So since a new windows always opens on the main screen, let's use this constructor in case there is a main screen. Otherwise we'll do a reasonable guess of the DPI.
Fixes #104

Auto-detect screen DPI 

---

Sources/tart/VMStorageLocal.swift

Otherwise there might an error like this during the very first clone:
```console
$: tart clone ghcr.io/cirruslabs/macos-monterey-vanilla:12.3.1 test-old
Error Domain=NSCocoaErrorDomain Code=4 "The file “test-old” doesn’t exist." UserInfo={NSFileOriginalItemLocationKey=file:///Users/fedor/.tart/vms/test-old/, NSURL=file:///Users/fedor/.tart/vms/test-old/, NSFileNewItemLocationKey=file:///var/folders/tq/8ph0hm796qg72yrfqx55685w0000gn/T/08537077-A16F-4F2F-9716-8DD26249D494, NSUnderlyingError=0x600003644870 {Error Domain=NSCocoaErrorDomain Code=4 "The file “08537077-A16F-4F2F-9716-8DD26249D494” doesn’t exist." UserInfo={NSURL=file:///var/folders/tq/8ph0hm796qg72yrfqx55685w0000gn/T/08537077-A16F-4F2F-9716-8DD26249D494, NSFilePath=/var/folders/tq/8ph0hm796qg72yrfqx55685w0000gn/T/08537077-A16F-4F …
```

Make sure VM directory exists before moving

---

.cirrus.yml
.goreleaser.yml

Xcode 14 Beta breaks something when building with a production configuration and Tart can't run a VM.

Build Debug Binary

---

Sources/tart/OCI/Manifest.swift
Sources/tart/VMDirectory+OCI.swift

OCI: store uncompressed disk size in manifest

---

.cirrus.yml

I've upgraded our persistent worker to Ventura but let's continue building and releasing Tart from within a Tart VM based of Monterey.

Build Tart inside a Tart VM

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

Still a noob in SwiftUI and Swift concurrency, but it seems on Ventura a task group is not actually running on main or something. Either way I think this change simplifies things but launching a VM in a task and then just continuing with either VNC or built-in graphics.

Fixes for Ventura

---

.goreleaser.yml

So that `tart run --with-softnet` works out of the box.
See https://github.com/cirruslabs/tart/pull/48#issuecomment-1161972483.

Homebrew: depend on Softnet package

---

Sources/tart/Commands/Run.swift
Sources/tart/VNCWrapper.swift

Let's start a VNC server but not force open Screen Sharing if `--no-graphics` is also passed.

Handle `tart run --no-graphics --vnc` properly

---

Sources/tart/Commands/Run.swift

Resolves https://github.com/cirruslabs/tart/issues/151.

tart run: return exit status 2 when VM is already running

---

Sources/tart/OCI/Registry.swift

It turns out that:
* the [AsyncHTTPClient](https://github.com/swift-server/async-http-client) package uses [`NIOTSEventLoopGroup()`](https://github.com/swift-server/async-http-client/blob/14fa6d944d88e5702ba630f8a8843966331fd944/Sources/AsyncHTTPClient/HTTPClient.swift#L103) as event loop group
* ...which uses [NIO Transport Services](https://github.com/apple/swift-nio-transport-services)
* ...which in turn uses [`Network.Framework`](https://developer.apple.com/documentation/network)
...which behaves wildly inefficient for reasons that can't be diagnosed easily without getting source code access:
However, we can force the AsyncHTTPClient to take a different path by manually specifying the event loop group provider.
This seems to be a simpler and faster alternative than …

OCI's HTTP client: prevent the usage of NIO Transport Services

---

Sources/tart/Commands/Login.swift

Resolves https://github.com/cirruslabs/tart/issues/166.

tart login: read whole stdin contents instead of just a line

---

Sources/tart/Commands/Login.swift
Sources/tart/Commands/Push.swift
Sources/tart/OCI/Registry.swift

Might be helpful for debugging against a local Docker Registry and also for #131.

OCI: support insecure registries and custom ports

---

Sources/tart/OCI/Registry.swift

Some registries still assumes it's a chunked upload and verifies the "chunk" size which is too big.

Do not include Content-Range for monolithic uploads

---

Sources/tart/VMDirectory+OCI.swift

This makes Tart use `mmap(2)`-backed `Data` and `InputFilter(.compress, ...)` logic from [Apple's documentation](https://developer.apple.com/documentation/accelerate/compressing_and_decompressing_data_with_input_and_output_filters#3328720), which fixes the memory leak and results in smooth memory usage overall:
(this shows a lifetime of a Tart instance that pushed a 120 GB disk to the registry)
Resolves https://github.com/cirruslabs/tart/issues/165.

OCI blob compression: fix Data memory leak when using InputFilter

---

Sources/tart/VMDirectory.swift
Sources/tart/VMStorageOCI.swift

Also contains a fix for digest calculation for remotely-retrieved manifests in f734f0b5d0ef6bf17922c5b568b5f27c00ecc5d0.
Resolves https://github.com/cirruslabs/tart/issues/37.

Implement garbage collection when deleting cached OCI VMs

---

Sources/tart/Commands/IP.swift
Sources/tart/MACAddressResolver/ARPCache.swift
Sources/tart/MACAddressResolver/MACAddress.swift
Sources/tart/VNC/ScreenSharingVNC.swift

This partially reverts the https://github.com/cirruslabs/tart/pull/141 to further diagnose #172 in the wild.
Resolves https://github.com/cirruslabs/tart/issues/172 for now.

tart ip: show a warning when DHCP lease and ARP cache entries mismatch

---

Sources/tart/URL+AccessDate.swift

Seems like `toUnit()` is causing rounding errors and returns `1222643699` instead of `1222643700` sometimes.

testGetAndSetAccessTime: fix flakiness

---

Sources/tart/Commands/Prune.swift
Sources/tart/VMStorageOCI.swift

This way when pulling the same image `ghcr.io/cirruslabs/macos-monterey-base:latest` over and over across it's lifetime we won't end up with a bunch of old images occupying the space on disk.
Also add hidden `tart prune --gc` flag to fix this manually.

Run garbage collection after each symlink and expose --gc in tart prune

---

Sources/tart/Credentials/HelperProgramCredentialsProvider.swift

Otherwise we get the following error:
```
% tart pull ghcr.io/cirruslabs/macos-monterey-vanilla:12.4
pulling ghcr.io/cirruslabs/macos-monterey-vanilla:12.4...
pulling manifest...
keyNotFound(CodingKeys(stringValue: "credHelpers", intValue: nil), Swift.DecodingError.Context(codingPath: [], debugDescription: "No value associated with key CodingKeys(stringValue: \"credHelpers\", intValue: nil) (\"credHelpers\").", underlyingError: nil))
```
With the following `~/.docker/config.json`:
```json
{
"auths": {
"ghcr.io": {},
"registry.gitlab.com": {}
},
"credsStore": "desktop"
}
```

Credential helpers: "credHelpers" map is optional in Docker's config

---

Sources/tart/Commands/Run.swift

I've tested `requestStop()` and it seems to be largely useless, because of this:
Resolves https://github.com/cirruslabs/tart/issues/204.

Terminate VM on GUI window close

---

.ci/create-pkg.sh
.goreleaser.yml

Seems goreleaser reset git state before submitting and therefore removes Tart.pkg

Create Apple Installer in dist folder

---

Sources/tart/Credentials/DockerConfigCredentialsProvider.swift
Sources/tart/OCI/Registry.swift

For some folks that don't want to fight with Keychain from Ansible but also OK with storing long lived credentials in plaintext.

Support plaintext auths from Docker config

---

Sources/tart/VMStorageOCI.swift

Otherwise it's weird we check $TMP but prune $TART_HOME

Check Tart Home for auto-pruning

---

Sources/tart/Commands/Prune.swift

To prevent accidental deletion of all cache entries 🤦‍♂️

Fix cache reclaimed bytes calculation

---

Sources/tart/VM.swift

Whilst attempting to use the directory share support, I encountered:  
`Error: error: directory sharing is only supported on macOS 13.0 (Ventura) or newer`
From that message it wasn't abundantly clear if it was my host or my guest that was not running the supported version of macOS

Clarify if guest or host is unsupported

---

Sources/tart/Commands/Clone.swift
Sources/tart/Config.swift
Sources/tart/FileLock.swift
Sources/tart/IPSWCache.swift
Sources/tart/VMStorageLocal.swift
Sources/tart/VMStorageOCI.swift
Tests/TartTests/FileLockTests.swift

Otherwise there exists a race condition that might result in two parallel `tart clone` instances creating two VMs with a similar MAC addresses.

tart clone: clone VM and generate MAC under a file lock

---

Sources/tart/Commands/Run.swift

See https://github.com/cirruslabs/tart/issues/232
If you create a `URL` such as  `URL(fileURLWithPath: "~/Downloads")` it doesn't automatically expand the tilde into the home directory. 
This PR uses NSString's `expandingTildeInPath` api to do the heavy lifting. 
Ideally `VZVirtualMachine` wouldn't hang and instead log if the directory share paths given didn't exist.

Handle tilde in path for directory share

---

Sources/tart/Commands/Run.swift

Follow on from https://github.com/cirruslabs/tart/pull/228
It is unclear when using the `dir` directory sharing that it requires guests to be running macOS 13 also. This PR tries to clarify that requirement in the help discussion output. 
Is there a way to read back out from the VM either running or prior to booting to know the version macOS? Would be nicer to report the failure as opposed to requiring the user read the docs.

Clarify requirements for `dir` argument

---

Sources/tart/Commands/IP.swift

I initially wanted a one-second wait but made a human mistake.
Fixes #249

Fixed wait delay for IP command

---

Sources/tart/Commands/Prune.swift

We now try to gather as much of the recent cache entries as possible that fit the budget before deleting the rest.
Resolves https://github.com/cirruslabs/tart/issues/271.

Fix tart prune --cache-budget logic

---

README.md

Packer has deprecated `json` configuration files, let's keep it updated.

Packer json configuration is deprecated

---

README.md

We can't use the regular images since we use Git LFS. Forgot to fix the main image as part of #237

Fixed Tart logo on GitHubMobile App

---

Sources/tart/Commands/Get.swift
Sources/tart/Root.swift

This PR implements a get command as outlined in https://github.com/cirruslabs/tart/issues/302. The output was formatted to look similar to other `tart` commands and is as follows:
```
> tart get m
cpu     memory  disk    display
4       8192MB  20GB    1024x768
```

Implement Get command

---

Sources/tart/VM.swift

Otherwise the memory usage is too high. This is also what causing the integration tests to fail: https://cirrus-ci.com/task/4605565639852032.

Fetch IPSWs via file

---

Sources/tart/Commands/Set.swift

This increases the max VM memory size from 64GB to ~9bn PB.

use 64bit int for memory

---

Sources/tart/Commands/Run.swift

Follow-up to https://github.com/cirruslabs/tart/pull/333.
See https://github.com/cirruslabs/tart/issues/323#issuecomment-1323636537 for more details.

tart run: do not check --disk lock for read-only attachments

---

Sources/tart/OCI/Registry.swift

See [WWW-Authenticate documentation on MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/WWW-Authenticate#auth-scheme).
Resolves https://github.com/cirruslabs/tart/issues/335.

OCI: WWW-Authenticate's scheme should be treated case-insensitive

---

Package.resolved
Package.swift

The working directory fix was merged: https://github.com/nicklockwood/SwiftFormat/pull/1317.

Switch to github.com/nicklockwood/SwiftFormat version 0.50.6

---

Sources/tart/Commands/List.swift

An attempt to solve #299 by providing a `--source` option to the `list` command.
Some example output:
```shell
tart list --help                
OVERVIEW: List created VMs
USAGE: tart list [--quiet] [--source <source>]
OPTIONS:
-q, --quiet             Only display VM names.
--source <source>       Only display VMs from the specified source (e.g. --source local, --source oci).
--version               Show the version.
-h, --help              Show help information.
```
```shell
$ tart list
Source	Name
local 	monterey-base
local 	ventura-base
local 	ventura-new
oci   	ghcr.io/cirruslabs/macos-ventura-base:latest
```
```shell
tart list --source oci
Source  Name
oci   	ghcr.io/cirruslabs/macos-ventura-base:latest
```
```shell
tart list --source foo
Unknown source: 'foo'
```
```shell
tart list …
```

Filter tart list by source

---

Sources/tart/Commands/Get.swift
Sources/tart/VMConfig.swift

#302 adds the ability to retrieve individual configuration items via the `get` command.
```
$tart get monterey-base --help 
OVERVIEW: Get a VM's configuration
USAGE: tart get <name> [--cpu] [--memory] [--disk-size] [--display]
ARGUMENTS:
<name>                  VM name.
OPTIONS:
--cpu                   Number of VM CPUs.
--memory              VM memory size in megabytes.
--disk-size             Disk size in gigabytes.
--display               VM display resolution in a format of
<width>x<height>. For example, 1200x800.
--version               Show the version.
-h, --help              Show help information.
```
```
$tart get monterey-base --cpu 
4
```
```
$tart get monterey-base --cpu --disk-size
Error: Options --cpu, --memory, --disk-size and --display are mutually exclusive
Usage: tart …
```

Get command

---

Sources/tart/VMStorageOCI.swift

Without this change the `tart push --populate-cache` doesn't work correctly, as it calls `link()` with the swapped arguments:
https://github.com/cirruslabs/tart/blob/d9f1c37cdda524fa1eb7cc72eb4039a58115993d/Sources/tart/Commands/Push.swift#L68

Fix inverted VMStorageOCI.link() logic

---

Sources/tart/Root.swift

Before:
```
% tart version
CommandError(commandStack: [tart.Root], parserError: ArgumentParser.ParserError.unexpectedExtraValues([(ArgumentParser.InputOrigin(_elements: Set([ArgumentParser.InputOrigin.Element.argumentIndex(0)])), "version")]))
```
After:
```
% tart version
Error: Unexpected argument 'version'
Usage: tart <subcommand>
See 'tart --help' for more information.
```

Fix ArgumentParser's exception printing

---

.goreleaser.yml
Sources/tart/Commands/ReportInstallation.swift
Sources/tart/Root.swift

Collect macOS version and device model.
The information reported to sentry is pretty anonymous and  doesn't contain information like username, hostname, etc. We are only interested in device model and macOS version.
Fixes #378

Collect installation information

---

Package.resolved
Package.swift
Sources/tart/Commands/Get.swift
Sources/tart/Commands/List.swift
Sources/tart/Formatter/Format.swift
Sources/tart/VMDirectory.swift

In the light of the upcoming `1.0.0` release and stabilizing of the API, let's introduce some breaking changes for the good.
Removed all the `--cpu`, `--memory`, `--disk` and `--display` flags and replaced with a single `--json` flag for machine-readable output.
Added `--json` option to the `list` command to output a single JSON list. Notably removed `--quite` flag since it seemed unnecessary.
Fixes #297

JSON output for get and list commands

---

Sources/tart/Commands/Prune.swift

This method is not marked as macOS 13.0+ only in the SDK for some reason, but is marked so [in the documentation](https://developer.apple.com/documentation/foundation/url/4013498-formatted).
Resolves https://github.com/cirruslabs/tart/issues/407.

Avoid URL.formatted() method

---

.ci/create-pkg.sh
.ci/pkg/scripts/postinstall
.cirrus.yml
.goreleaser.yml

Build the `*.pkg` again and also notarize the archive uploaded to releases. Notarization tool does not support `*.tar.gz` so I switched to `*.zip` which is supported by both Gorealser and Homebrew.
I also added a Dry Run task that dry runs everything and notarizes everything for contributors with the right permissions.

Build Package installer and notarize release archive

---

.goreleaser.yml

Since trying to notarized the release archive as mentioned [here](https://github.com/cirruslabs/tart/pull/415#issuecomment-1450545065) seems breaking the validation.
Fixes #441

Switch back to .tar.gz

---

Sources/tart/Commands/IP.swift
Sources/tart/MACAddressResolver/ARPCache.swift
Sources/tart/MACAddressResolver/Leases.swift
Tests/TartTests/MACAddressResolverTests.swift

Haven't seen any reports of the `arp` vs DHCP issues so I think it's reasonable to remove the warning and allow to customize the resolution strategy.
This way if one will want to access a Tart VM running on a remote host it will be possible:
```bash
remote-host:$ tart run --net-bridged=en0 my-vm
remote-host:$ tart ip --resolver=arp my-vm
192.168.192.222
local-host-on-the-same-network:$ ssh admin@192.168.192.222
```

Allow to choose IP resolution strategy

---

Sources/tart/Commands/Run.swift

This is the simplest way I've found to send the cancellation signal to the `Task` that runs the VM.
To prevent weird error messages like in https://github.com/cirruslabs/tart/issues/428#issuecomment-1449354509.
Works with https://github.com/cirruslabs/softnet/pull/23.

Graceful Softnet termination

---

Package.resolved
Package.swift

This upgrade might improve the quality of Swift stacktraces a bit, see https://github.com/getsentry/sentry-cocoa/releases/tag/8.0.0.
Support for Swift Concurrency is still not implemented, though: https://github.com/getsentry/sentry-cocoa/issues/1919.

Upgrade Sentry to 8.3.3

---

.ci/create-pkg.sh
.cirrus.yml
.goreleaser.yml

Last time it broke in https://github.com/cirruslabs/tart/issues/441. The theory is that notarization of the `.pkg` before after notarizaation of the binary was breaking validation on Apple side.
This attempt does build the .pkg before we do all the dance with gon ang goreleaser.

Build pkg again

---

Sources/tart/Commands/Push.swift
Sources/tart/VMDirectory.swift
Sources/tart/VMStorageHelper.swift
Sources/tart/VMStorageLocal.swift
Sources/tart/VMStorageOCI.swift

Resolves https://github.com/cirruslabs/tart/issues/423.
Supersedes https://github.com/cirruslabs/tart/pull/461.

tart push: allow pushing OCI VMs from the cache too

---

Sources/tart/Commands/Login.swift

To support `echo $PASSWORD | tart login --username $USERNAME --password-stdin $REGISTRY` and avoid the need for `echo -n` which seems to be a gotcha for users: https://github.com/cirruslabs/tart/issues/483#issuecomment-1534348869.
This is similar to what `docker login` does: https://github.com/docker/cli/blob/054343be3855fea3375f185392128f6c54d9a39d/cli/command/registry/login.go#L97-L98.

tart login: trim newline characters at the end of --password-stdin

---

Sources/tart/Commands/Run.swift
Sources/tart/Root.swift

So that automation tools will have an easier time picking up the errors.

Print errors to stderr

---

docs/quick-start.md

They seem to just be leftovers from previous versions of the docs, so a small cleanup could be helpful.

Replace mentions of Monteray with Ventura in quickstart guide

---

Sources/tart/Commands/Prune.swift

Problem: we were accessing prunable's `sizeBytes()` method after deleting it.
Solution: only access `sizeBytes()` before deleting the prunable.

Fix "file “config.json” couldn’t be opened" error when pruning

---

.goreleaser.yml

While we're still at #503, this will at least improve the current state of things.
Advice from https://github.com/goreleaser/goreleaser/issues/4143#issuecomment-1607975728.

.goreleaser.yml: remove Tart binary from the root of the archive

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Prune.swift
Sources/tart/VMStorageOCI.swift

To avoid cases when OCI images take large space amounts and prevent the new VMs from being cloned.

tart clone: try to reclaim disk space if needed

---

Sources/tart/VMStorageOCI.swift

Right now on a pull we always acquire a lock for a registry host. This is problematic. For example, a worker can be pulling `ghcr.io/cirruslabs/macos-ventura-xcode:15-beta-2` image when a new request will come to pull `ghcr.io/cirruslabs/macos-ventura-xcode:latest` if needed.
In this situation, even though `ghcr.io/cirruslabs/macos-ventura-xcode:latest` is already cached and linked, `tart pull` will wait for a lock because the lock is per registry host.
This change optimistically check if there is something to do at all before acquiring a lock.

Optimistically check if we need to do anything on a pull

---

Sources/tart/Platform/Darwin.swift

I guess [my comment was accurate](https://github.com/cirruslabs/tart/pull/524/files#r1239939939). Fixes #534
Tested by running `ghcr.io/cirruslabs/macos-monterey-base:latest` locally on a Sonoma host.

Fixed mouse/keyboard on Monterey guest

---

Package.resolved
Package.swift
Sources/tart/PIDLock.swift
Sources/tart/VMDirectory.swift

To address PERSISTENT-WORKERS-1B.
Also update Sentry package to the latest version.

PIDLock: check open(2) error

---

Sources/tart/Commands/Push.swift
Sources/tart/OCI/Registry.swift
Sources/tart/VMDirectory+OCI.swift

Replaces `baseURL.host!`, hopefully fixes https://github.com/cirruslabs/tart/issues/543

Add `host` to `Registry` taking `port` into consideration

---

Sources/tart/Credentials/EnvironmentCredentialsProvider.swift

When specified, Tart will additionally check if the host that the image is being pulled from matches that environment variable, and if not, the credential evaluation will continue.
This will allow to fix https://github.com/cirruslabs/gitlab-tart-executor/issues/28#issuecomment-1628971742.

Introduce TART_REGISTRY_HOSTNAME

---

Sources/tart/Commands/Prune.swift

I noticed when I ran `prune --older-than=7` `tart` deleted some images I didn't expect it to (because I used them lately). I looked into `Prune` and it seems the sign is wrong on the `olderThan` argument handling.

Fix `prune --older-than` deleting all cache

---

.cirrus.yml

Apparently it's not possible to share debug files cross projects. So let's upload to both of them. To one we use in production and one we use for testing.

Upload debug files to both Sentry projects

---

Sources/tart/Commands/Run.swift
Tests/TartTests/DirecotryShareTests.swift

To utilize `VZSingleDirectoryShare` which seems more stable than `VZMultipleDirectoryShare`.
We've been having reports from users that mounted directories occasionally return "no such file" errors when building large projects. I took a stab at reproducing the issue by running https://github.com/devMEremenko/XcodeBenchmark in a mounted directory:
```bash
tart run --dir=workdir-test:~/workspace-temp/XcodeBenchmark ventura-xcode
```
And I was able to reproduce the "no such file" error on the first try! After looking into the issue I decided to try `VZSingleDirectoryShare` as this PR changes and to my pleasant surprise it all worked like a charm the next run. So it seems there is a bug in `VZMultipleDirectoryShare` integration with virtiofs. Since in most cases users only mount a single …

Allow mounting a single directory without a name

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Prune.swift

Sometimes people have an image that is greater than half of the disk itself. In that case such image will be pulled and prunned right away.
This change makes sure that an image that is being cloned from is not pruned right away.

Don't delete an initiator of pruning

---

docs/theme/overrides/home.html

Seems in 2.0.0 release they broke looping. Right now animation on https://tart.run/ is always looping even without `loop` property. I was able to disable it, so I just downgraded to the last known working version.

[skip ci] Downgrade Lottie Player

---

docs/licensing.md

1. Currently the license tier explanation doesn't mention the licensing limits imposed for [Orchard](https://github.com/cirruslabs/orchard).
2. The call to action should be made more clearer because looking for a `licensing@cirruslabs.org` email on the page is not obvious. Ideally a big green button, but moving instructions to a separate "Get the license" section probably should suffice for now.

Clarify licensing

---

Sources/tart/Credentials/DockerConfigCredentialsProvider.swift

This way for #581 we don't need to specify a fully quialified URL and can simply use the following `~/.docker/config.json`:
```json
{
"credsStore": "ecr-login"
}
```
Related to https://github.com/docker/cli/issues/2928

Support Docker's `credsStore`

---

Sources/tart/VMStorageHelper.swift

Also upgrade `isFileNotFound()` do detect underlying errors.
See https://github.com/cirruslabs/orchard/pull/125.

Return exit code 2 on RuntimeError.VMDoesNotExist

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Pull.swift
Sources/tart/Commands/Push.swift
Sources/tart/OCI/Digest.swift
Sources/tart/OCI/Layerizer/Disk.swift
Sources/tart/OCI/Layerizer/DiskV1.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/OCI/Manifest.swift
Sources/tart/OCI/Registry.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMStorageHelper.swift
Sources/tart/VMStorageOCI.swift
Tests/TartTests/LayerizerTests.swift

This turned out to be more complicated that I've expected, so any hints to simplify this are welcome.
Things that still need to be fixed and checked:
* ~~apply DRY to the logic of temporary files creation in `LayerizerTests` and implement their cleanup~~ → https://github.com/cirruslabs/tart/pull/589/commits/b4b79d390600ce9a994fd3675c6775695943fb2d
* ~~check if the `DiskV2.pull()` is really parallelizing pulls and not blocking due to e.g. `Digest.hash()`~~ → https://github.com/cirruslabs/tart/pull/589#issuecomment-1686848822 + https://github.com/cirruslabs/tart/pull/589#issuecomment-1686855945
* ~~check that the resumable pulls indeed work and maybe add an integration test for that~~ → https://github.com/cirruslabs/tart/pull/589#issuecomment-1687697649
* ~~check if we need to lock the …

Improved format for fast and efficient pulls from remote OCI-registry

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

This way AWS customers will be able to benefit from fast local SSDs on the machines. Right now a EC2 Mac Instances is booted from a EBS volume which is fast but is not as fast as a local SSD. Running Tart VMs of the EBS volume totally works but for advanced integrators it might be reasonable to mount a local SSD as a disk to a VM and run their workloads on it.
There are a few caveats to this use case:
1. Block devices persist state and should be cleaned up.
2. `tart` binary should be run as root to access disks in `/dev`.
3. Only Sonoma hosts are supported. Ventura guests are fine.
4. A block device can only be attached to a single VM.
PS I tried but failed miserably to find a way to escalate permissions to open a file descriptor for the disk with `root` permission out of Tart process …

Support block devices on Sonoma

---

.cirrus.yml
README.md
docs/blog/posts/2023-04-28-orchard-ssh-over-grpc.md
docs/integrations/cirrus-cli.md
docs/integrations/github-actions.md
docs/integrations/gitlab-runner.md
docs/integrations/vm-management.md
docs/quick-start.md
integration-tests/test_run.py
scripts/run-signed.sh

Also tried to put everything about Cirrus Runners in one place rather than having the information spreaded between https://tart.run and https://github.com/apps/cirrus-runners.
Plus updated docs to use Sonoma.

Document XL Cirrus Runners

---

Resources/tart-dev.entitlements

Needed to run the Tart in the Instruments.app, otherwise Instruments.app will report an error.

tart-dev.entitlements: add "com.apple.security.get-task-allow"

---

Sources/tart/Fetcher.swift
Sources/tart/OCI/Registry.swift

Should help with the memory usage when `pull`'ing.

Fetcher.fetchViaFile(): use an mmap(2)-ed file, similarly to DiskV1

---

.cirrus.yml

Seems it installas 1.x version instead of 2.x. Sentry's documentation [recommends to use their script](https://docs.sentry.io/product/cli/installation/?original_referrer=https%3A%2F%2Fwww.google.com%2F#automatic-installation).

Don't install Sentry CLI via brew

---

docs/integrations/gitlab-runner.md

Simply just adds specifically VM in the gitlab runner docs to avoid confusion of where the build and cache dirs are.
Some context for this - when I initially read it I took no notice and changed the dirs to be something like `/Users/ec2-user/...` and it broke, so just a simple improvement to the docs.
Thanks!

fix docs to specify inside VM for gitlab runner

---

Sources/tart/Commands/Run.swift
scripts/run-signed.sh

This was likely not caught because the `run-signed.sh` script used during development didn't wrap the executable in an application bundle, which is what's done when Tart is installed on user systems.
The app bundle triggers macOS to show a Dock icon, which we now hide explicitly by setting an activation policy of prohibited:
https://developer.apple.com/documentation/appkit/nsapplication/activationpolicy/prohibited

Hide dock icon in no graphics mode

---

docs/quick-start.md

Resolves https://github.com/cirruslabs/tart/issues/666.

Document available VM images on the website

---

Sources/tart/Commands/Run.swift
Sources/tart/Commands/Stop.swift
Sources/tart/Commands/Suspend.swift
Sources/tart/VMDirectory.swift
Sources/tart/VMStorageHelper.swift
Sources/tart/VMStorageLocal.swift

And introduce a `VMDirectory.lock()` method to avoid duplication of the `PIDLock(lockURL: vmDir.configURL)` snippet.

tart delete: prevent the deletion of running VMs

---

Sources/tart/VMStorageOCI.swift

The [`fileExists()`](https://developer.apple.com/documentation/foundation/filemanager/1415645-fileexists) method always resolves symbolic links and will return `false` even if the link itself exists:
>If the final element in path specifies a symbolic link, this method traverses the link and returns true or false based on the existence of the file at the link destination.
This is an issue when `tart pull` detects that there isn't enough space for the new image, removes the old `sha256:` and then tries to create a link for the news image and fails:
>Persistent worker failed to start the task: tart isolation failed: failed to create VM cloned from "[ghcr.io/cirruslabs/macos-sonoma-base:latest](http://ghcr.io/cirruslabs/macos-sonoma-base:latest)": tart command returned non-zero exit code: …

OCI storage: unconditionally remove the old link when link()'ing

---

Sources/tart/Commands/Create.swift

So that invocation like `tart create macos --from-ipsw=~/UniversalMac_14.1_23B74_Restore.ipsw` would work.

tart create --from-ipsw: expand tilde (~) in path

---

Sources/tart/Commands/Set.swift
Sources/tart/VMDirectory.swift
Sources/tart/VMStorageHelper.swift

See https://github.com/cirruslabs/linux-image-templates/pull/7.

tart set: bring back the --disk-size command-line argument

---

docs/licensing.md

[docs] Improved table of content for `licensing.md`

---

docs/faq.md

Tart is now arguably more popular and there is no need to have Anka compartment first in the FAQ. It's not a frequent question anymore.

[docs] Deprioritize Anka

---

README.md
docs/theme/overrides/home.html

Removed Anka mentions and Codemagic/Testingbot since we don't know if they still use Tart.

Some SEO optimizations

---

Sources/tart/Commands/Rename.swift

This seems like the intention of the error message, it should show the name of the VM that you are trying to set as the new name.
If you run:
`tart rename firstVM secondVM`
It currently prints:
`failed to rename VM firstVM, target VM firstVM already exists`
Now it will print:
`failed to rename VM firstVM, target VM secondVM already exists`

Improve rename error message

---

Sources/tart/Commands/Run.swift

From a discussion in #728 it appeared that having both `--graphics` and `--no-graphics` is a bit confusing.
`--graphics` was introduced in #248 to support having both VNC and UI for debugging Packer plugin in cirruslabs/packer-plugin-tart#21. This is because `--vnc` flag has a side effect of hiding UI which I think was wrong in retrospective. One can run `tart run --vnc --no-graphics`. In most of the cases this is automated via Alfred or something like that.
Now we have so many arguments that IMO it's worth to remove `--graphics` for overall consistency in arguments: everything is enabled by default and can be disabled via `--no-*` flags.

Do not magically set `--no-graphics` when `--vnc` is passed

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

The default behavior is to run with audio if we're showing the Tart UI window. It can be disabled with --no-audio.
When running without a UI Window, audio is disabled, but can be enabled via --audio.

Add command line option to run without audio

---

Sources/tart/Commands/Run.swift
Tests/TartTests/DirecotryShareTests.swift

This reduces the cognitive complexity of `DirectoryShare` parsing code by moving the options parsing logic (`ro` and `tag`) into a separate method and also allows specifying options in any order (e.g. `/Users/admin/build:tag=foo-bar,ro`).
Also, the docs for `--dir` now looks like this:
The `[name:]path[:ro,tag=virtiofs-mount-tag]` format unfortunately does not allow us to express the available option combinations properly, so I think it would be a nice idea to reduce the cognitive load and abstract away the notion of "options" altogether into `discussion` section.

Simpler DirectoryShare parsing and --dir documentation improvements

---

Sources/tart/Commands/Run.swift
Tests/TartTests/DirecotryShareTests.swift

Allow to override VirtioFS tag for shared directories

---

Sources/tart/MACAddressResolver/Leases.swift
Tests/TartTests/LeasesTests.swift

Before we were *trying* to handle condition this by filtering out expired leases: https://github.com/cirruslabs/tart/blob/3f17884ac2bdba56f5688537aa6da4d14533e3f4/Sources/tart/MACAddressResolver/Leases.swift#L42-L44
However, it seems that it's possible to have two un-expired leases for the same MAC-address at the same time.
So let's prefer a newer lease over the older one when a duplicate is found.
See https://github.com/cirruslabs/tart/issues/739 for more details.

DHCP MAC-address resolver: handle duplicate leases

---

docs/blog/posts/2023-02-11-changing-tart-license.md
docs/licensing.md

5x jump in price from Gold to Platinum is a bit too high. Most of known large deployments target 200-300 hosts. Let's accommodate such customers by lowering Platinum tier.

Update Platinum Tier

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Get.swift
Sources/tart/Commands/List.swift
Sources/tart/Commands/Prune.swift
Sources/tart/Prunable.swift
Sources/tart/URL+Prunable.swift
Sources/tart/VMDirectory.swift

Right now we show only actual size of files on disk which excludes empty blocks of the recently introduced sparced format in #671. This makes impossible to get info about disk size that we just set via `tart set`.
Here is an example of `tart list` output before the change:
```
Source Name                                                                                                            Size State
local  sonoma-base                                                                                                     22   stopped
local  sonoma-vanilla                                                                                                  18   stopped
local  sonoma-xcode                                                                                                    67 …
```

Show both size and actual size of files

---

Sources/tart/Platform/Darwin.swift

It seems that the experimental VNC server uses a different code path and only considers the first input device in list, which causes the VNC to not process any input on macOS Monterey guests.
Tested on `UniversalMac_12.6.1_21G217_Restore.ipsw`, resolves https://github.com/cirruslabs/packer-plugin-tart/issues/128.
I've also checked that the previous/next page gesture works on macOS Sonoma guests in Safari.
Needs fixes from https://github.com/cirruslabs/tart/pull/746 for the build to succeed.

Prefer USB keyboard and screen coordinate pointing devices

---

.ci/pkg/scripts/postinstall
Resources/Info.plist
scripts/run-signed.sh

So signing and `embedded.provisionprofile` work as expected.
Related to #746

Lowercase `tart.app`

---

integration-tests/test_run.py

This could've detected the regression introduced in https://github.com/cirruslabs/tart/pull/746.

integration-tests: test_run() with --no-graphics

---

Sources/tart/Commands/Run.swift

Reverts #732 and marks `--graphics` as private to not ever show in help.

Revert "Do not magically set --no-graphics when --vnc is passed 

---

Sources/tart/Commands/Get.swift

Can be useful to know from outside the VM.

Report operating system in tart get

---

.goreleaser.yml

At the point which homebrew generates the completions the exec script has not been made executable yet, so we can't rely on that.

Generate shell completions by calling tart.app executable

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Get.swift
Sources/tart/Commands/List.swift
Sources/tart/Commands/Run.swift
Sources/tart/Commands/Stop.swift
Sources/tart/VMDirectory.swift

https://github.com/cirruslabs/tart/commit/202a6264b1c3413abd8da4aa5df2a11025d0af1c ensures that the `tart stop` behavior introduced in https://github.com/cirruslabs/tart/pull/321 still works.
https://github.com/cirruslabs/tart/commit/ce0ac404da1168c7266a4697a2c10acfe42f7fbe resolves https://github.com/cirruslabs/tart/issues/782.

tart stop: throw RuntimeError.VMNotRunning consistently and use enumeration instead of strings

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Delete.swift
Sources/tart/Commands/Export.swift
Sources/tart/Commands/FQN.swift
Sources/tart/Commands/Get.swift
Sources/tart/Commands/IP.swift
Sources/tart/Commands/Push.swift
Sources/tart/Commands/Rename.swift
Sources/tart/Commands/Run.swift
Sources/tart/Commands/Set.swift
Sources/tart/Commands/Stop.swift
Sources/tart/Commands/Suspend.swift
Sources/tart/ShellCompletions/ShellCompletions.swift

resolves https://github.com/cirruslabs/tart/issues/778
I think I added completions to all commands where it makes sense.
In the process I also found [a bug in swift-argument-parser](https://github.com/apple/swift-argument-parser/issues/631)

Add shell completions

---

Sources/tart/Commands/Run.swift

Fixes #759
So people can experiment with mounting NBDs before we can decide if it's viable to put the whole VM on it.

Allow mounting NBD disks

---

docs/quick-start.md

Resolves https://github.com/cirruslabs/tart/issues/791.

Document how to mount the shared directory on Linux at boot time

---

Sources/tart/Commands/Run.swift
Sources/tart/VMStorageHelper.swift

There's an alternative way to achieve the correct permissions using `chmod $USER /dev/diskX`.
Also, use `open(2)` to discern between various types of errors and give a specific error message.
Related to https://github.com/cirruslabs/tart/issues/724.

tart run: do not require root to mount a block device

---

Sources/tart/Commands/Run.swift

Before only suspendable VMs were getting checked. Not sure why. It makes sense to check all.

Check all VMs for MAC collision

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

We were letting the CancellationError bubble up all the way until
it terminated app, which meant we didn't hit the shutdown code
in run(), stopping the VM and the network.
We now catch CancellationError and proceed to gracefully shut down.
We only stop the VM if it's still running, as a VM that has been
stopped via the menu can't be stopped again.

Gracefully stop vm on tart stop

---

Sources/tart/Commands/Set.swift

To generate new MAC address and/or serial number for a given VM.

Introduce `--random-mac` and `--random-serial` flags for `tart set`

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Create.swift
Sources/tart/Commands/List.swift
Sources/tart/Commands/Rename.swift
docs/integrations/vm-management.md
docs/quick-start.md

This PR clarifies that Tart doesn't run random Docker images from OCI registries. It also capitalizes OCI in `tart list` cuz I think it looks better that way.

Minor documentation improvements.

---

Sources/tart/OCI/Layerizer/DiskV2.swift

With this PR, we'll yield exactly 2 layers per GB of VM disk image when doing `tart push`, which at the moment equates to:
* 100 layers for `ghcr.io/cirruslabs/macos-sonoma-base:latest` instead of the current 38 layers
* 256 layers for `ghcr.io/cirruslabs/macos-runner:sonoma` instead of the current 162 layers
This slightly increases the bookkeeping costs, but allows for better deduplication in `tart pull` (in the upcoming PR).
Our calculations have shown that current layer deduplication ratios are:
* 0% for distant and 63% for nearby tags for `ghcr.io/cirruslabs/macos-sonoma-base:latest` images
* 0% for distant and 14% for nearby tags for `ghcr.io/cirruslabs/macos-runner:sonoma` images
With the fixed-size chunks of 500 MB, the deduplication ratios will be as follows:
* 46% for distant and …

tart push: use fixed size chunks to allow for better deduplication

---

Sources/tart/LocalLayerCache.swift
Sources/tart/OCI/Layerizer/Disk.swift
Sources/tart/OCI/Layerizer/DiskV1.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMStorageOCI.swift

A follow-up to https://github.com/cirruslabs/tart/pull/821.

tart pull: try to re-use local VM image layers to speed-up the pulling

---

integration-tests/requirements.txt

To fix the build failing.
See https://github.com/psf/requests/issues/6707 for more details.

integration-tests: downgrade "requests" package to 2.31.0

---

Sources/tart/VMStorageOCI.swift

Resolves https://github.com/cirruslabs/tart/issues/827.

VMStorageOCI: percent-encode the colon in RemoteName's host

---

Sources/tart/Commands/Run.swift

For macOS this brings up a dialog, asking the user if they are sure they want to shut down, which makes this less useful for automated graceful shutdowns, but it may behave better on Linux, and there might be ways to instruct macOS to not ask the user, so it's still a nice feature, and aligns with the SIGUSR1 for suspend, and SIGINT for non-graceful shutdown.

Hook SIGUSR2 to requestStop

---

Sources/tart/Commands/Run.swift
Sources/tart/Commands/Set.swift

To create a VM with a custom disk:
```shell
tart create --linux xcode-16.0
tart set --disk <path to DMG> xcode-16.0
```
To mount this VM after pushing (and pulling it):
```shell
tart run --disk ghcr.io/cirruslabs/xcode:16.0 <VM>
```

Support customizing VM disks and mounting remote VMs in `tart run`

---

Sources/tart/OCI/Manifest.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMDirectory.swift
Sources/tart/VMStorageOCI.swift

This is accomplished by saving the OCI VM image manifests on "tart pull" in "manifest.json" file and then using them on successive "tart pull"'s to find the best candidate that results in the most de-duplication, measured in bytes.

tart pull: choose across multiple VM images to deduplicate against

---

Sources/tart/VM.swift

To prevent crashes in the guest when playing or recording audio and (1) no permission is given or (2) `--no-audio` is used.
Suspend seems to work fine.

--no-audio: only disable the source and sink

---

Package.resolved
Package.swift
Sources/tart/Commands/List.swift
Sources/tart/URL+Prunable.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMDirectory.swift

Improvement to the APFS deduplication logic which checks whether a disk image file `mayShareFileContent` with some other file, and then we put a custom attribute to track the deduplication since there is no way to get this information from APFS itself.
It's not 100% accurate but given that OCI cache is immutable the actual disk usage can only be lover than that.

APFS reuse UX/DX improvements

---

Package.resolved
Package.swift
Sources/tart/Commands/List.swift
Sources/tart/LocalLayerCache.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/URL+Prunable.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMDirectory.swift
Sources/tart/VMStorageOCI.swift

To be honest, I'm not a fan of this approach, because it's incredibly hard to measure the real-world impact of this, both in terms of CPU overhead and disk usage savings<sup>1</sup>.
The reason being that these variables are highly influenced by the contents of the base VM image (from which we're de-duplicating) and by the contents of the VM image to be pulled, yet we only have a few publicly available to run the tests on.
<sup>1</sup>: It feels that in some cases even losses, because we can't skip writing a zero block if the file we're basing off contains some other data in that place.

tart pull: try to re-use APFS blocks by cloning the base image

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

See https://github.com/cirruslabs/tart/pull/875#issuecomment-2265359773.
Also added support for passing the synchronization mode to macOS root disk in https://github.com/cirruslabs/tart/pull/879/commits/2338e0beb0fa2a03de462dc1e7bf1958a8728765.

tart run: replace --sync with --root-disk-opts

---

Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/OCI/Registry.swift

By issuing [HEAD requests](https://github.com/opencontainers/distribution-spec/blob/main/spec.md#checking-if-content-exists-in-the-registry) to the registry before doing the actual upload.
Resolves https://github.com/cirruslabs/tart/issues/886.

tart push: avoid uploading blobs if they are already present

---

Sources/tart/Commands/Run.swift
Sources/tart/Platform/Darwin.swift
Sources/tart/Platform/Platform.swift
Sources/tart/VM.swift

This reverts commit 017592075fc044a7e588fdaf62e190d18162d909. Since Sequoia is not crashing anymore.
Should fix #856

Revert "Drop Monterey Support (#843)"

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

With the current behaviour VMs do have audio devices but they don't pass-through signal to host which can lead to issues like https://github.com/actions/runner-images/issues/9330 . 
With this change there will be just no audio at all but commands like `say "hello"` work fine. So people don't need to apply the workaround for the permission dialog at all.

Completely disable audio devices in case of `--no-audio`

---

Package.resolved
Package.swift

https://github.com/getsentry/sentry-cocoa/pull/4297 could possibly fix sporadic Sentry SDK initialization crashes.

Package.swift: bump Sentry SDK to 8.36.0 + upgrade other packages

---

Package.resolved
Package.swift
Sources/tart/OCI/Reference/Generated/ReferenceBaseListener.swift
Sources/tart/OCI/Reference/Generated/ReferenceLexer.swift
Sources/tart/OCI/Reference/Generated/ReferenceListener.swift
Sources/tart/OCI/Reference/Generated/ReferenceParser.swift

To avoid the following warning when parsing a reference (e.g. when running `tart pull`):
```
ANTLR Tool version 4.11.1 used for code generation does not match the current runtime version 4.13.2
```

Re-generate ANTLR files using ANTLR 4.13.2

---

Sources/tart/PIDLock.swift
Sources/tart/VMStorageHelper.swift

Current behavior:
```
% tart delete non-existent ; echo $?
failed to open lock file file:///Users/edi/.tart/vms/non-existent/config.json: No such file or directory
1
```
With this PR:
```
% tart delete non-existent ; echo $?
the specified VM "non-existent" does not exist
2
```
Related to https://github.com/cirruslabs/packer-plugin-tart/issues/168.

tart delete: return human-friendly error when local VM doesn't exist

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Pull.swift
docs/faq.md

And use consistent automatic pruning documentation in `--help` of `tart clone` and `tart pull`.

Document automatic pruning in FAQ

---

Sources/tart/Commands/Clone.swift
Sources/tart/Commands/Pull.swift
Sources/tart/OCI/Layerizer/Disk.swift
Sources/tart/OCI/Layerizer/DiskV1.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/VMDirectory+OCI.swift
Sources/tart/VMStorageOCI.swift

As noted in https://github.com/cirruslabs/tart/pull/864, deduplication is a somewhat controversial feature that might result in noticeably slower pulls with larger network speeds (think 10 Gbps) due to disk reads and comparisons needed.
Also, hole punching mechanism used for deduplication can presumably result in APFS performance degradation later, when running the cloned VMs.
On the other hand, typical disk space savings observed for Cirrus Labs images are around 12 GB per pulled VM, which might not worth the extra complexity involved and potential performance implications.

tart {clone,pull}: make deduplication opt-in

---

Sources/tart/URL+AccessDate.swift

Otherwise we get some nonsense from `SecCopyErrorMessageString()` in `explanation()` when the error occurs.
Related to `PERSISTENT-WORKERS-43`.

utimes(2): use errno to explain the error

---

Sources/tart/Commands/Pull.swift
Sources/tart/VMStorageOCI.swift

Otherwise it's possible for the VM to be garbage collected by some other Tart process.
Possibly related to `PERSISTENT-WORKERS-44`.

tart pull: open the VM directory after pulling under a lock

---

Sources/tart/VMStorageOCI.swift

No one is going to throw `Retryable` anyway.
This makes the logic similar to the `tart push` side of things:
https://github.com/cirruslabs/tart/blob/cd0f238a678bc534ea8a94b8dfd945feecc487b8/Sources/tart/OCI/Layerizer/DiskV2.swift#L37-L42
Resolves https://github.com/cirruslabs/tart/issues/944.

tart pull: retry if we get URLError

---

Sources/tart/Commands/Run.swift

Instead, the "Control" menu gets removed, which resides at index `2`.

tart run: do not remove "Edit" menu as it's not present anymore

---

Sources/tart/Commands/Run.swift
Sources/tart/Commands/Set.swift
Sources/tart/VMConfig.swift

A simpler approach with direct `VMConfig.displayAutoReconfigure` access, inverted flag (to support prepending `--no-*`) and backwards compatibility (according to [the truth table](https://github.com/cirruslabs/tart/pull/951#issuecomment-2483611581)).
/cc @Fred78290
Resolves https://github.com/cirruslabs/tart/pull/951.

tart set: support --{,no-}display-auto-reconfigure

---

Package.resolved
Package.swift
Sources/tart/Fetcher.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/OCI/Registry.swift
Sources/tart/VM.swift

This makes `tart pull` times comparable to skopeo, see benchmarks below.
Will post the [profiling results](https://github.com/cirruslabs/tart/blob/main/PROFILING.md#using-xctrace1) tomorrow.
Related to https://github.com/cirruslabs/tart/issues/963.
Docker Registry on local machine was used with the following `config.yml`:
```yaml
version: 0.1
log:
fields:
service: registry
storage:
cache:
blobdescriptor: inmemory
filesystem:
rootdirectory: /tmp/registry
http:
addr: :8080
```
To start it:
```shell
git clone https://github.com/distribution/distribution.git
cd distribution
go run cmd/registry/main.go serve config.yml
```
Then, push the image to be later pulled in benchmarks:
```shell
tart push --insecure macos-sequoia-base 127.0.0.1:8080/a/b:latest
```
The following patch was applied to …

tart pull: 284% faster pulls with default concurrency setting

---

Sources/tart/Fetcher.swift

Otherwise we start to periodically get RST's from GitHub, possibly because of too many connection opens, which has an effect of cancelling previously received bytes.
These RST's can be observed in tcpdump/Wireshark or Console, emitted from the libusrtcp.dylib library, com.apple.network subsystem, for the Tart process:
```
tcp_input [C59.1.1.1:3] flags=[R] seq=1805021659, ack=0, win=0 state=CLOSED rcv_nxt=1805021659, snd_una=1752355607
```
You can also observe the "Received Bytes" in "Activity Monitor" for the Tart process while pulling `ghcr.io/cirruslabs/macos-runner:sequoia, and this value will periodically` decrease.

Fetcher: re-use URLSession

---

Sources/tart/Fetcher.swift
Sources/tart/OCI/Registry.swift
Sources/tart/VM.swift

Resolves https://github.com/cirruslabs/tart/issues/971.

Registry: limit the text output on unexpected status code

---

docs/orchard/deploying-controller.md

Quote from [StackOverflow answer](https://stackoverflow.com/a/59400069/9316533):
>Surprise!! ... Creating a Compute Engine through the console doesn't just run a single gcloud command, it runs a few. Specifically:
>```
>gcloud beta compute ... instances create instance-1 ...
>gcloud compute ... firewall-rules create default-allow-http ...
>gcloud compute ... firewall-rules create default-allow-https ...
>```
So, when a user attempts to deploy Orchard Controller on an empty GCP project using `gcloud`, the traffic to TCP port 443 won't flow because these rules are only created through the web UI.
Resolves https://github.com/cirruslabs/orchard/issues/227.

docs: a firewall rule needs to be created when deploying Orchard to GCE

---

Sources/tart/Commands/Run.swift

Softnet's side: https://github.com/cirruslabs/softnet/pull/70.
Note that Softnet limitations still apply. This means that for exposing the VMs ports to the LAN, you might probably want to add something like `--net-softnet-allow=192.168.0.0/24` or use `--net-softnet-allow=0.0.0.0/0` if you don't need Softnet protection.
See https://github.com/cirruslabs/tart/discussions/855.

tart run: introduce --net-softnet-expose

---

Sources/tart/Commands/Run.swift
Sources/tart/Credentials/DockerConfigCredentialsProvider.swift
Sources/tart/OCI/Layerizer/DiskV1.swift
Sources/tart/OCI/Layerizer/DiskV2.swift
Sources/tart/VM.swift
Sources/tart/VMDirectory+OCI.swift

The [`write(_:)`](https://developer.apple.com/documentation/foundation/filehandle/1410936-write) is deprecated crashes the program instead of throwing an exception.
Resolves https://github.com/cirruslabs/tart/issues/989.

Always use write(contentsOf:) instead of write(_:)

---

.goreleaser.yml

See https://github.com/cirruslabs/tart/issues/998#issuecomment-2596105372.

.goreleaser.yml: caveats stanza with DHCP fix information

---

Sources/tart/Commands/Set.swift

Otherwise it crashes:
```
% tart set --random-serial linux
Could not cast value of type 'tart.Linux' (0x105010648) to 'tart.Darwin' (0x10500ec18).
zsh: abort      tart set --random-serial linux
```

Make tart set --random-serial no-op for Linux VMs

---

Sources/tart/Commands/Run.swift
Sources/tart/VM.swift

And document which packages need to be installed on these operating systems.
Resolves https://github.com/cirruslabs/tart/issues/14.

Enable clipboard sharing on macOS too

---

Sources/tart/Commands/Create.swift
Sources/tart/Commands/Export.swift
Sources/tart/Commands/Import.swift
Sources/tart/Commands/List.swift
Sources/tart/Commands/Prune.swift
Sources/tart/Commands/Run.swift

See https://github.com/apple/swift-argument-parser/issues/761 for more details.
Resolves https://github.com/cirruslabs/tart/issues/1063.

Fix unescaped commas in generated ArgumentParser completions

---

Sources/tart/Commands/Login.swift
Sources/tart/Credentials/CredentialsProvider.swift
Sources/tart/Credentials/DockerConfigCredentialsProvider.swift
Sources/tart/Credentials/EnvironmentCredentialsProvider.swift
Sources/tart/Credentials/KeychainCredentialsProvider.swift
Sources/tart/Credentials/StdinCredentials.swift
Sources/tart/OCI/Registry.swift

https://github.com/cirruslabs/tart/issues/1129 was likely caused by an invalid `~/.docker/config.json`, see https://github.com/cirruslabs/tart/issues/1129#issuecomment-3305016175.
Do not fail fast when iterating over credential helpers and simply log an attributed error instead.
Before:
```
pulling ghcr.io/cirruslabs/macos-sonoma-base:latest...
pulling manifest...
Error: dataCorrupted(Swift.DecodingError.Context(codingPath: [], debugDescription: "The given data was not valid JSON.", underlyingError: Optional(Error Domain=NSCocoaErrorDomain Code=3840 "Unexpected end of file" UserInfo={NSDebugDescription=Unexpected end of file})))
```
After:
```
pulling ghcr.io/cirruslabs/macos-sonoma-base:latest...
pulling manifest...
Failed to retrieve credentials using Docker configuration credentials …
```

Do not fail fast when iterating over credential providers

---

docs/.markdownlint.yml
docs/blog/posts/2023-02-11-changing-tart-license.md
docs/blog/posts/2023-04-25-orchard-ga.md
docs/blog/posts/2023-04-28-orchard-ssh-over-grpc.md
docs/blog/posts/2023-09-20-tart-2.0.0.md
docs/blog/posts/2023-10-06-tart-on-aws.md
docs/blog/posts/2023-11-03-cirrus-runners-dashboard.md
docs/integrations/buildkite.md
docs/integrations/cirrus-cli.md
docs/orchard/architecture-and-security.md
docs/orchard/deploying-controller.md
docs/orchard/integration-guide.md
docs/orchard/quick-start.md
docs/orchard/using-orchard-cli.md

Also fix MkDocs warnings w.r.t. absolute instead of relative links in https://github.com/cirruslabs/tart/commit/d06c713e0740c37762e00deb2a6596290675b6f3.

Document automatic resources set by the Orchard Worker

---

Sources/tart/Commands/Run.swift

Running `tart run` as `root` has been problematic for many users, especially starting from macOS 15 (Sequoia).

Do not recommend running "tart run" as root to mount block devices
