- .goreleaser.yml
- README.md
> .goreleaser(brews): depend on macOS Monterey

- README.md
It was a bit confusing to folks not familiar with Cirrus CLI. Reworked the documentation to better introduce Cirrus CLI.
> Reworked CI integration documentation

- Sources/tart/Commands/Pull.swift
Resolves https://github.com/cirruslabs/tart/issues/36.
> tart pull: be more liberal when accepting local image as argument

- README.md
> Add Geekbench report link

- README.md
> Document VM location on disk

- Sources/tart/Commands/List.swift
Resolves https://github.com/cirruslabs/tart/issues/88.
> tart list: fix heading order

- Sources/tart/Commands/List.swift
Resolves https://github.com/cirruslabs/tart/issues/89.
> Sort "tart list" by default

- .ci/set-version.sh
- .goreleaser.yml
See https://github.com/cirruslabs/tart/pull/92#issuecomment-1131956381.
> .ci/set-version.sh: use temporary file

- Sources/tart/OCI/Manifest.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VMDirectory+OCI.swift
- Tests/TartTests/RegistryTests.swift
- Tests/TartTests/Util/RegistryRunner.swift
Resolves https://github.com/cirruslabs/tart/issues/34.
> Registry functional/integration tests

- Sources/tart/Commands/IP.swift
- Sources/tart/Commands/Run.swift
So copy/paste is working. For example, `tart run --vnc latest`.
Related to #14
> Option to run with VNC

- Sources/tart/Commands/Run.swift
> Allow VNC for Recovery mode

- Sources/tart/Config.swift
- Sources/tart/OCI/Manifest.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VMConfig.swift
- Sources/tart/VMDirectory+OCI.swift
- Tests/TartTests/RegistryTests.swift
Resolves https://github.com/cirruslabs/tart/issues/133.
> OCI: make sure annotations are sorted

- Sources/tart/Credentials/KeychainCredentialsProvider.swift
> Credentials: update Keychain entry if it already exists

- Sources/tart/Commands/Run.swift
- Sources/tart/VNC/FullFledgedVNC.swift
- Sources/tart/VNC/ScreenSharingVNC.swift
- Sources/tart/VNC/VNC.swift
Resolves https://github.com/cirruslabs/tart/issues/152.
> Move full-fledged VNC support to --experimental-vnc

- Sources/tart/Config.swift
- Sources/tart/VM.swift
- Sources/tart/VMStorageLocal.swift
- Sources/tart/VMStorageOCI.swift
Useful for https://github.com/cirruslabs/tart/issues/131.
> Introduce TART_HOME

- Sources/tart/Commands/Run.swift
- Sources/tart/VM.swift
Resolves https://github.com/cirruslabs/tart/issues/150.
> tart run: introduce --disk option

- Sources/tart/Credentials/KeychainCredentialsProvider.swift
Resolves https://github.com/cirruslabs/tart/issues/160.
> tart login: only store one credential per registry

- Sources/tart/VM.swift
> Configure audio devices to pass through the signal from/to the host

- Sources/tart/OCI/Registry.swift
> OCI: gcr.io fixes

- Sources/tart/OCI/Registry.swift
Follow up to an attempt in #169
> Fixed potential infinity auth

- Package.resolved
- Package.swift
- Sources/tart/Commands/Push.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VMDirectory+OCI.swift
- Tests/TartTests/RegistryTests.swift
As described in https://docs.docker.com/registry/spec/api/#pushing-a-layer
Should help with #158
> Support chunked uploads

- .goreleaser.yml
In case someone tries to install Tart. Fixes #176
> Friendly error message on Intel

- Package.resolved
- Package.swift
- Sources/tart/Commands/List.swift
- Sources/tart/Commands/Prune.swift
- Sources/tart/IPSWCache.swift
- Sources/tart/Prunable.swift
- Sources/tart/Root.swift
- Sources/tart/URL+AccessDate.swift
- Sources/tart/URL+Prunable.swift
- Sources/tart/VM.swift
- Sources/tart/VMDirectory.swift
- Sources/tart/VMStorageOCI.swift
- Tests/TartTests/URLAccessDateTests.swift
Resolves https://github.com/cirruslabs/tart/issues/33.
> Introduce "tart prune" command

- Sources/tart/Commands/Clone.swift
- Sources/tart/Commands/Pull.swift
See https://github.com/cirruslabs/tart/pull/174.
> tart {pull,clone}: add missing --insecure support

- .cirrus.yml
> Build and release from Ventrura

- Package.swift
- Sources/tart/Commands/Create.swift
- Sources/tart/OCI/Manifest.swift
- Sources/tart/Platform/Architecture.swift
- Sources/tart/Platform/Darwin.swift
- Sources/tart/Platform/Linux.swift
- Sources/tart/Platform/OS.swift
- Sources/tart/Platform/Platform.swift
- Sources/tart/VM.swift
- Sources/tart/VMConfig.swift
- Sources/tart/VMDirectory+OCI.swift
The workflow is as follows:
```shell
tart create --linux ubuntu
tart run --disk focal-desktop-arm64.iso ubuntu
tart run ubuntu
```
Resolves #62.
> Linux support

- Sources/tart/Commands/Prune.swift
- Sources/tart/VM.swift
See https://github.com/cirruslabs/tart/issues/62#issuecomment-1225992065.
> Make UnsupportedOSError more user-friendly

- README.md
See https://github.com/cirruslabs/tart/discussions/195#discussioncomment-3473452.
> README.md: clarify "Pulling a Remote Image" section

- README.md
- Sources/tart/Platform/Darwin.swift
- Sources/tart/Platform/Linux.swift
- Sources/tart/Platform/Platform.swift
- Sources/tart/VM.swift
> Support trackpad on macOS

- Sources/tart/Commands/Login.swift
- Sources/tart/Credentials/HelperProgramCredentialsProvider.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/Softnet.swift
- Sources/tart/Utils.swift
> Support Docker Helpers

- Sources/tart/Commands/Create.swift
- Sources/tart/Commands/Run.swift
- Sources/tart/VM.swift
- Sources/tart/VMConfig.swift
Works both on macOS and Linux.
Requires macOS Ventura.
Resolves https://github.com/cirruslabs/tart/issues/13.
> Directory sharing support

- .cirrus.yml
- .goreleaser.yml
- gon.hcl
> Sign release binaries

- .cirrus.yml
- .goreleaser.yml
The installer will install tart binary to `/usr/local/bin/tart`
Fixes #153
> Create Apple Installer

- README.md
- Resources/Users/CirrusCI.png
- Resources/Users/Codemagic.png
- Resources/Users/TestingBot.png
> Document Adopters

- README.md
Resolves https://github.com/cirruslabs/tart/issues/235.
> Document NAT subnet change procedure

- Sources/tart/Commands/Clone.swift
- Sources/tart/Commands/Create.swift
- Sources/tart/Config.swift
- Sources/tart/Root.swift
- Sources/tart/VMDirectory.swift
- Sources/tart/VMStorageOCI.swift
Resolves https://github.com/cirruslabs/tart/issues/222.
> Self-hosted temporary directory

- Sources/tart/Commands/Rename.swift
- Sources/tart/Root.swift
- Sources/tart/VMStorageLocal.swift
Resolves https://github.com/cirruslabs/tart/issues/227.
> Introduce "tart rename" command to rename VMs

- Resources/tart.entitlements
- Sources/tart/Commands/Run.swift
- Sources/tart/Network/Network.swift
- Sources/tart/Network/NetworkBridged.swift
- Sources/tart/Network/NetworkShared.swift
- Sources/tart/Network/Softnet.swift
- Sources/tart/VM.swift
Resolves https://github.com/cirruslabs/tart/issues/243.
> tart run: introduce --net-bridged

- Sources/tart/Commands/IP.swift
- Sources/tart/MACAddressResolver/Leases.swift
Resolves https://github.com/cirruslabs/tart/issues/253.
> tart ip: keep waiting for the /var/db/dhcpd_leases file to appear

- Sources/tart/Commands/Create.swift
- Sources/tart/IPSWCache.swift
- Sources/tart/VM.swift
Resolves https://github.com/cirruslabs/tart/issues/251.
> tart create: support fetching URLs specified in the --from-ipsw option

- Package.resolved
- Package.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VM.swift
- Sources/tart/VMDirectory+OCI.swift
- Tests/TartTests/RegistryTests.swift
Should help with https://github.com/cirruslabs/tart/issues/234 and prevent things like https://github.com/cirruslabs/tart/pull/168.
> Ditch AsyncHTTPClient in favor of URLSession

- Sources/tart/VM.swift
A follow-up to https://github.com/cirruslabs/tart/pull/260.
> Don't download IPSWs into memory

- Package.resolved
- Package.swift
- Sources/tart/Commands/Prune.swift
- Sources/tart/Prunable.swift
- Sources/tart/Root.swift
- Sources/tart/URL+Prunable.swift
- Sources/tart/VMDirectory.swift
- Sources/tart/VMStorageOCI.swift
Resolves https://github.com/cirruslabs/tart/issues/239.
> Log cache pruning to $TART_HOME/tart.log

- Sources/tart/OCI/Registry.swift
The actual issue was in improper use of [`URLSession.bytes()`](https://developer.apple.com/documentation/foundation/urlsession/3767351-bytes), where the `URLSession.AsyncBytes` was not unwound in all cases.
Resolves https://github.com/cirruslabs/tart/issues/264.
> Plug URLSession.bytes() memory leak

- Sources/tart/Commands/Run.swift
For consistency's sake with `--net-bridged`.
> tart run: deprecate --with-softnet and introduce --net-softnet

- Sources/tart/OCI/Registry.swift
> Relax status code acceptance

- Sources/tart/OCI/Registry.swift
> OCI: always read channel until end

- README.md
So that it works out of the box for most people.
> README.md: more realistic Packer HCL example

- Sources/tart/Fetcher.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VM.swift
A PoC for https://github.com/cirruslabs/tart/pull/280#issuecomment-1300105314.
> OCI: pull blobs via file

- Sources/tart/Fetcher.swift
Resolves https://github.com/cirruslabs/tart/issues/295.
> Fetcher: do not use cookies to avoid CSRF checks

- Sources/tart/VMDirectory.swift
To better communicate what's wrong, examples:
* https://github.com/cirruslabs/tart/issues/290
* https://github.com/cirruslabs/tart/pull/309#discussion_r1018166988
> Improve UninitializedVMDirectoryError()

- Sources/tart/Commands/Run.swift
- Sources/tart/Commands/Stop.swift
- Sources/tart/PIDLock.swift
- Sources/tart/Root.swift
Resolves https://github.com/cirruslabs/tart/issues/315.
> Introduce "tart stop"

- Sources/tart/Commands/Stop.swift
See https://github.com/cirruslabs/tart/pull/316#issuecomment-1311556674.
> tart stop: return a different exit code when VM is not running

- .cirrus.yml
- Sources/tart/VM.swift
- integration-tests/conftest.py
- integration-tests/docker_registry.py
- integration-tests/requirements.txt
- integration-tests/tart.py
- integration-tests/test_clone.py
- integration-tests/test_create.py
- integration-tests/test_delete.py
- integration-tests/test_oci.py
- integration-tests/test_rename.py
> Integration tests

- Sources/tart/VM.swift
Resolves https://github.com/cirruslabs/tart/issues/329.
> VZVirtualMachineDelegate implementation: show the error details

- README.md
- Resources/Users/Background.png
- Resources/Users/HowToAddYourself.md
- Resources/Users/Suran.png
- Resources/Users/Symflower.png
- Resources/Users/ahrefs.png
> Document list of users

- Sources/tart/Commands/Run.swift
It seems that the `Virtualization.Framework` tries to acquire a lock on the disk passed by us and hangs.
One obvious thing we can do is to check the lock before starting the actual VM and bail out if the lock is acquired by someone else.
Resolves https://github.com/cirruslabs/tart/issues/323.
> tart run: check if the disks are locked

- Sources/tart/Commands/Run.swift
- Sources/tart/VM.swift
A simpler approach to https://github.com/cirruslabs/tart/pull/287.
> Rosetta support

- README.md
Resolves https://github.com/cirruslabs/tart/issues/301.
> README.md: document --dir

- .cirrus.yml
- Package.resolved
- Package.swift
> Fix SwiftFormat's URL/glob mishandling

- Sources/tart/OCI/Registry.swift
Resolves https://github.com/cirruslabs/tart/issues/335.
> Registry: include port when looking up credentials

- README.md
Whilst getting up to speed with the project and making my first PR there were a few fixes, normalizations and additions I wanted to make.
> Doco fixups

- .cirrus.yml
- Package.resolved
- Package.swift
- Sources/tart/CI/CI.swift
- Sources/tart/Commands/Clone.swift
- Sources/tart/Commands/Create.swift
- Sources/tart/Commands/Delete.swift
- Sources/tart/Commands/Get.swift
- Sources/tart/Commands/IP.swift
- Sources/tart/Commands/List.swift
- Sources/tart/Commands/Login.swift
- Sources/tart/Commands/Prune.swift
- Sources/tart/Commands/Pull.swift
- Sources/tart/Commands/Push.swift
- Sources/tart/Commands/Rename.swift
- Sources/tart/Commands/Run.swift
- Sources/tart/Commands/Set.swift
- Sources/tart/Commands/Stop.swift
- Sources/tart/MACAddressResolver/ARPCache.swift
- Sources/tart/Root.swift
- Sources/tart/VMStorageHelper.swift
Best viewed with the "Hide whitespace" checkbox ticked.
See https://github.com/cirruslabs/cirrus-cli/issues/587.
> Sentry integration

- .cirrus.yml
> .cirrus.yml: install Sentry CLI

- Sources/tart/Root.swift
Apparently `--help` works via exceptions 🤷‍♂️
Fixes #360
> Fixed --help

- Sources/tart/Commands/Run.swift
> Removed `--with-softnet` flag

- Sources/tart/Root.swift
> Ignore GC errors

- .cirrus.yml
- Sources/tart/Commands/Run.swift
- Sources/tart/Network/Softnet.swift
- Sources/tart/VMStorageHelper.swift
Alternative to https://github.com/cirruslabs/tart/pull/413.
Resolves https://github.com/cirruslabs/tart/issues/358.
> Try to set a SUID bit on Softnet using Sudo before failing

- docs/stylesheets/landing.css
- docs/theme/overrides/home.html
> Show installation count on the landing page

- docs/licensing.md
Since the repo is not yet public
> Removed link to Orchard

- mkdocs.yml
> Enable RSS feed for blog

- .goreleaser.yml
To fix "code has no resources but signature indicates they must be present" which is caused by attributes.
Fixes #438
> Remove binary attributes

- Sources/tart/Commands/Run.swift
- Sources/tart/Serial.swift
- Sources/tart/VM.swift
- Sources/tart/VMConfig.swift
Hi, I wanna contribute the controller for virtual machine via serial port.
User can now add this field into config.json to use serial port
```
{
...
"serial": true
}
```
VM will create a serial device in **/dev/ttys00X**
user can use **screen /dev/ttys00X 115200** command to connect to the virtual machine.
> support ZVirtioConsoleDevice for linux vm

- Sources/tart/Commands/Export.swift
- Sources/tart/Commands/Import.swift
Resolves https://github.com/cirruslabs/tart/issues/419.
> tart export: make export path optional

- Sources/tart/Commands/Get.swift
- Sources/tart/Commands/List.swift
- Sources/tart/VMDirectory.swift
See https://github.com/cirruslabs/orchard/pull/70#discussion_r1151842805.
> tart list: show if the VM is running or not

- .ci/create-pkg.sh
- .cirrus.yml
- .goreleaser.yml
- gon.hcl
> Use release configuration for binaries

- Sources/tart/VMDirectory+Archive.swift
Resolves https://github.com/cirruslabs/tart/issues/452.
> tart import: fix import failing due to SIGBUS

- .ci/create-pkg.sh
- .goreleaser.yml
Another attempt at #457 but I've created a separate bundle id for the pkg so it's not colliding with the binary for Brew.
> Revert pkg

- Sources/tart/Commands/IP.swift
> Improve `tart ip` error message

- Sources/tart/Commands/Push.swift
Simplification that I implied in https://github.com/cirruslabs/tart/pull/465#discussion_r1159038157
> Refactored pushing of OCI images under new tag

- Sources/tart/Commands/IP.swift
Otherwise most automations will fail because there's a race between the time a VM is created and the time `tart run` acquires a lock.
> tart ip: wait for the VM to start if --wait was set

- Package.resolved
- Package.swift
- Sources/tart/DeviceInfo/DeviceInfo.swift
- Sources/tart/OCI/Registry.swift
Resolves https://github.com/cirruslabs/tart/issues/409.
> Set User-Agent header for OCI HTTP requests

- Sources/tart/Platform/Darwin.swift
- Sources/tart/Platform/Linux.swift
- Sources/tart/Platform/Platform.swift
- Sources/tart/VM.swift
> Improve error reporting for unsupported host OS version

- docs/licensing.md
- mkdocs.yml
I realised we didn't add a proper link to Orchard
> Minor docs improvements

- README.md
CI Integration is really good, thank you!
> Add PITS Global Data Recovery Services to the list of companies

- docs/licensing.md
For both Tart and Orchard
[skip ci]
> Clarify Licensing Use Limitation

- .goreleaser.yml
Resolves https://github.com/cirruslabs/tart/issues/518.
> .goreleaser.yml: include LICENSE file in the release archive

- .cirrus.yml
- Sources/tart/Commands/Run.swift
Only works for Sonoma (or higher) hosts running Sonoma (or higher) guests.
> Enable automatic display reconfiguration for Sonoma

- Sources/tart/OCI/Registry.swift
This fixes issue https://github.com/cirruslabs/tart/issues/529
> Adds the OCI access_token fallback field

- .goreleaser.yml
> Run `gon` right after building

- Sources/tart/Commands/Prune.swift
- Sources/tart/VMStorageLocal.swift
Resolves https://github.com/cirruslabs/tart/issues/542.
> tart prune: allow pruning local VMs with --entries=vms

- Sources/tart/Commands/Run.swift
- Sources/tart/VM.swift
See https://github.com/cirruslabs/tart/pull/560.
> Retrieve VM's IP for use in VNC after the VM is started #2

- docs/licensing.md
> Provide license usage examples

- .cirrus.yml
- Sources/tart/Commands/Run.swift
- Sources/tart/Network/Network.swift
- Sources/tart/Network/NetworkBridged.swift
- Sources/tart/Network/NetworkShared.swift
- Sources/tart/Network/Softnet.swift
- Sources/tart/VM.swift
> Multiple bridged interfaces

- Sources/tart/Commands/Login.swift
- Sources/tart/Commands/Logout.swift
- Sources/tart/Credentials/KeychainCredentialsProvider.swift
- Sources/tart/Root.swift
Resolves https://github.com/cirruslabs/tart/issues/576.
> Introduce "tart logout" command

- Sources/tart/Commands/Run.swift
> No bridged network interfaces by default

- integration-tests/requirements.txt
- integration-tests/tart.py
- integration-tests/test_clone.py
- integration-tests/test_create.py
- integration-tests/test_delete.py
- integration-tests/test_rename.py
- integration-tests/test_run.py
This test would have catched the https://github.com/cirruslabs/tart/issues/585 earlier.
> Add a simple integration test for "tart run"

- Sources/tart/VM.swift
...to check if we already have the `.ipsw` file cached or not.
Resolves https://github.com/cirruslabs/tart/issues/598.
> tart create --from-ipsw: do a HEAD instead of a GET first

- docs/blog/posts/2023-09-20-tart-2.0.0.md
`brew update` updates homebrew. Need to use `brew upgrade` for the tart package specifically.
> Change brew update to brew upgrade

- docs/blog/posts/2023-09-20-tart-2.0.0.md
Resolves https://github.com/cirruslabs/tart/issues/607.
> web: fix GitLab Runner integration link

- Sources/tart/Platform/Darwin.swift
> `--suspendable` devices fallback on Ventura host

- .cirrus.yml
Resolves PERSISTENT-WORKERS-1A.
> .cirrus.yml: add an execution_lock: for integration tests

- Sources/tart/VM.swift
See https://github.com/cirruslabs/tart/issues/147#issuecomment-1741586962.
> tart run: disable console device when --suspendable is requested

- Sources/tart/Credentials/StdinCredentials.swift
Resolves https://github.com/cirruslabs/tart/issues/617.
> tart: bump max password characters from 256 to 1024

- Sources/tart/Platform/Darwin.swift
See https://developer.apple.com/documentation/virtualization/vzmacauxiliarystorage/3816043-init
> Removed usage of deprecated APIs

- Sources/tart/OCI/Layerizer/DiskV2.swift
There is a suspicion that this might leak memory
> Don't forget to finalize output stream

- Sources/tart/OCI/Layerizer/DiskV2.swift
Currently, `tart push` might consume substantial amounts of memory when pushing an image such as `tart create --linux linux`:
This could've been solved by using an `autoreleasepool`:
```patch
diff --git a/Sources/tart/OCI/Layerizer/DiskV2.swift b/Sources/tart/OCI/Layerizer/DiskV2.swift
index 04e8c0c..f0b9d46 100644
--- a/Sources/tart/OCI/Layerizer/DiskV2.swift
+++ b/Sources/tart/OCI/Layerizer/DiskV2.swift
@@ -124,18 +124,20 @@ class DiskV2: Disk {
// Create a compressing filter that we will terminate upon
// reaching ``Self.layerLimitBytes`` of compressed data
let compressingFilter = try InputFilter(.compress, using: .lz4, bufferCapacity: bufferSizeBytes) { (length: Int) -> Data? in
-      if compressedData.count >= Self.layerLimitBytes {
-        return nil
-      }
+      try …
```
> DiskV2.push(): map disk into memory to avoid large allocations

- Sources/tart/OCI/AuthenticationKeeper.swift
- Sources/tart/OCI/Registry.swift
We also need to prevent multi-entrancy here:
https://github.com/cirruslabs/tart/blob/f4bc02d1751dd5ad447619515e7d73a9efc2d7e6/Sources/tart/OCI/Registry.swift#L313-L319
...but let's do that in a separate PR to avoid complicating things.
> Introduce AuthenticationKeeper actor to serialize authn modification

- Sources/tart/Commands/Run.swift
To allow guest to capture things like Cmd+Tab.
Fixes #636
> Introduce `--capture-system-keys` flag

- Sources/tart/Commands/Run.swift
> Properly enter main even loop in headless mode

- docs/licensing.md
Fixes https://github.com/cirruslabs/tart/discussions/652
> Document ECR Public Mirror

- docs/quick-start.md
> Use ssh from our tap

- Package.resolved
- Package.swift
- Sources/tart/MACAddressResolver/Lease.swift
- Sources/tart/MACAddressResolver/Leases.swift
- Tests/TartTests/LeaseTest.swift
- Tests/TartTests/LeasesTests.swift
- Tests/TartTests/MACAddressResolverTests.swift
Resolves https://github.com/cirruslabs/tart/issues/668.
> MAC address resolver: skip expired leases

- docs/faq.md
> Document how to unlock the Keychain over SSH

- Sources/tart/VM.swift
- Sources/tart/VMConfig.swift
> tart create --linux: allow scaling VM down to 1 CPU and 256 MiB

- Sources/tart/Commands/Run.swift
Resolves https://github.com/cirruslabs/tart/issues/682.
> tart run: disable dynamic display reconfiguration for Linux

- Sources/tart/VMDirectory.swift
...when the size is not changed.
> tart set: make --disk-size change idempotent

- docs/quick-start.md
See https://github.com/cirruslabs/tart/discussions/708.
> Document default admin/admin credentials

- docs/quick-start.md
> [docs] Resize linux images after cloning

- .cirrus.yml
- .goreleaser.yml
- Sources/tart/Commands/Create.swift
- Sources/tart/Commands/Run.swift
- Sources/tart/Platform/Darwin.swift
- Sources/tart/VM.swift
- Sources/tart/VMConfig.swift
- gon.hcl
- integration-tests/test_create.py
So we can use it to build amd64 images for Vetu to use for [Cirrus Runners](https://cirrus-runners.app/).
`#if`s are ugly but I didn't find a better way. I wish Swift had something like `build` in Go.
> Build x86 binary

- Sources/tart/Commands/Run.swift
See https://github.com/cirruslabs/softnet/pull/34.
> tart run: introduce --net-softnet-allow command-line argument

- Sources/tart/Commands/Run.swift
> Fixed `--no-graphics` mode

- .goreleaser.yml
To fix missing icon since #746
> Pack additional resources into brew releases

- .goreleaser.yml
Same as https://github.com/cirruslabs/orchard/pull/157 and https://github.com/cirruslabs/cirrus-cli/pull/696
Learn more: https://apple.github.io/swift-argument-parser/documentation/argumentparser/installingcompletionscripts
> Set up automatic installation of shell completion files

- Sources/tart/VM.swift
We wrap the installation with a withTaskCancellationHandler, which ensures that the SIGINT signal handling code in main() will trigger a cancellation of the installer.
As the VZMacOSInstaller must be both created and interacted with on the VM's queue, which in our case is the main queue, we need to move the logic to a separate function tagged with @MainActor. This makes sense either way, as it cleans up the code a bit.
> Support cancellation of installation process

- Package.resolved
- Package.swift
- Sources/tart/Root.swift
- Sources/tart/VMStorageOCI.swift
> Sentry: upgrade and attach command-line arguments

- .cirrus.yml
- Package.resolved
- Package.swift
- Sources/tart/Commands/Suspend.swift
- Sources/tart/Credentials/KeychainCredentialsProvider.swift
- Sources/tart/Network/Network.swift
- Sources/tart/Network/NetworkBridged.swift
- Sources/tart/Network/NetworkShared.swift
- Sources/tart/Network/Softnet.swift
- Sources/tart/OCI/Layerizer/DiskV2.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VM.swift
- Tests/TartTests/TokenResponseTests.swift
Plus updated all the dependencies and Swift Tools.
Fixes #785
> Fixed Swift Warning

- Package.resolved
- Package.swift
- Sources/tart/VMStorageOCI.swift
Resolves https://github.com/cirruslabs/tart/issues/783.
> tart pull: retry VM pull with exponential backoff

- Sources/tart/Commands/Run.swift
And show "Suspend" menu item based on `--suspnedable` flag
Fixes #796
> Validate Suspendability

- Sources/tart/Commands/Run.swift
See https://github.com/NetworkBlockDevice/nbd/blob/master/doc/uri.md#nbd-uri-scheme
Fixes #792
> Support all NBD schemas

- Sources/tart/Commands/Run.swift
To avoid future confusion.
Also de-indented the `else {` to follow a similar fast-exit pattern that we have for NBD attachments.
> Fix pathHasMode() and only check for S_IFBLK

- Sources/tart/Commands/Run.swift
- Sources/tart/VNC/FullFledgedVNC.swift
- Sources/tart/VNC/ScreenSharingVNC.swift
- Sources/tart/VNC/VNC.swift
Resolves https://github.com/cirruslabs/tart/issues/810.
> tart run: resolve VM's IP using ARP when using --net-bridged and --vnc

- .cirrus.yml
- docs/quick-start.md
> Update manual installation instructions

- Sources/tart/VMDirectory+OCI.swift
- Sources/tart/VMStorageHelper.swift
With more information about the underlying issue.
Relates to #833
> Friendly decompression error message

- .cirrus.yml
> Fixed GoReleaser 2.0.0

- Sources/tart/Commands/Run.swift
- Sources/tart/Platform/Darwin.swift
- Sources/tart/Platform/Platform.swift
- Sources/tart/VM.swift
People will still be able to run and SSH into Monterey VMs or use VNC but pointing devices/keyboard won't work.
Fixes #841
> Drop Monterey Support

- Sources/tart/Commands/Run.swift
See https://github.com/cirruslabs/tart/pull/837#issuecomment-2174206394 for more details.
Supersedes https://github.com/cirruslabs/tart/pull/837.
> tart run: pick up --net-softnet-allow when using --net-host

- Sources/tart/Commands/Push.swift
- Sources/tart/VMStorageLocal.swift
Also prevent pushing of a running VM
Fixes #860
> Do not prune running VMs

- Sources/tart/Commands/Login.swift
- Sources/tart/OCI/Registry.swift
- Sources/tart/VMStorageHelper.swift
- Tests/TartTests/Util/RegistryRunner.swift
Resolves https://github.com/cirruslabs/tart/issues/859.
> tart login: better error when an improperly formatted host is provided

- Sources/tart/OCI/Layerizer/DiskV2.swift
Needed to test https://github.com/cirruslabs/tart/pull/864.
> DiskV2: change layer size to 512 * 1024 * 1024 bytes

- Sources/tart/Commands/Push.swift
- Sources/tart/OCI/Layerizer/Disk.swift
- Sources/tart/OCI/Layerizer/DiskV1.swift
- Sources/tart/OCI/Layerizer/DiskV2.swift
- Sources/tart/VMDirectory+OCI.swift
- Tests/TartTests/LayerizerTests.swift
See https://github.com/cirruslabs/tart/issues/867#issuecomment-2236331212.
> tart push: support --concurrency command-line argument

- Sources/tart/Commands/Run.swift
See https://github.com/cirruslabs/tart/discussions/871.
> tart run: support disabling disk synchronization for --disk

- Sources/tart/Commands/Run.swift
Otherwise `nbd://` URLs get corrupted and change to `nbd:/`, which is not a valid URL.
Resolves https://github.com/cirruslabs/tart/issues/877.
> tart run: delay tilde (~) expansion until we're dealing with local path

- Sources/tart/OCI/Layerizer/DiskV2.swift
- Sources/tart/VMStorageOCI.swift
Resolves https://github.com/cirruslabs/tart/issues/885.
> tart push: re-try when encountering errors when pushing disk layers

- docs/orchard/deploying-controller.md
- docs/orchard/managing-cluster.md
Also fix the `Backups` section as it was incomplete.
> docs(orchard): document Kubernetes and systemd service deployment methods

- Sources/tart/Commands/Run.swift
- Sources/tart/VMStorageHelper.swift
> tart run: provide a hint with names of other running VMs

- Resources/Info.plist
Resolves https://github.com/cirruslabs/tart/issues/908.
> Info.plist: set CFBundleName and CFBundleDisplayName to Tart

- Sources/tart/OCI/Registry.swift
Problem: normally, the reason we get the HTTP 401 when working with OCI registries is the initial lack of token, in which case `AuthenticationKeeper` will have no `Authentication` set, and the `authenticationKeeper.header()` will return `nil`.
However, sometimes the cause for the HTTP 401 is that the scopes mismatch, and since the `AuthenticationKeeper` now already has `Authentication`, we'll happily add it to a request for a new token (not just for a regular OCI request):
https://github.com/cirruslabs/tart/blob/c0b20932c7a04ad7517980c04d6c0f34891c2488/Sources/tart/OCI/Registry.swift#L419-L421
This results in a token request with two values in the `Authorization` and causes HTTP 400 for e.g. GitLab Registry.
Solution: never consider `AuthenticationKeeper` when making a request for a new …
> Registry: prevent double authorization when getting a new token

- .ci/set-version.sh
See https://github.com/cirruslabs/tart/discussions/920.
> CI: populate CFBundleShortVersionString in Info.plist

- Tests/TartTests/Util/RegistryRunner.swift
https://docs.docker.com/reference/cli/docker/container/run/#publish
> RegistryRunner: explicitly listen on localhost

- docs/faq.md
Could be useful in some cases.
> FAQ: document /var/db/dhcpd_leases and its removal

- Sources/tart/Commands/Clone.swift
Currently we try to reclaim the allocated bytes instead, which makes little sense since they're _already_ allocated.
In reality, we can observe the following VM image sizes:
| Image                                          | Full size | Allocated size |
|------------------------------------------------|-----------|----------------|
| `ghcr.io/cirruslabs/macos-runner:sonoma`       | `340 GB`    | `221 GB`         |
| `ghcr.io/cirruslabs/macos-runner:sequoia`      | `320 GB`    | `203 GB`         |
| `ghcr.io/cirruslabs/macos-sonoma-base:latest`  | `50 GB`     | `24 GB`          |
| `ghcr.io/cirruslabs/macos-sequoia-base:latest` | `50 GB`     | `26 GB`          |
In the first two cases, we probably want to free `119 GB` and `117 GB` instead of `221 GB` and `203 GB`, accordingly.
In the …
> tart clone: only reclaim unallocated bytes

- Sources/tart/Commands/Run.swift
Resolves https://github.com/cirruslabs/tart/issues/992.
> tart run: clarify --net-softnet-expose limitations w.r.t. PF rdr rules

- benchmark/README.md
- benchmark/internal/command/root.go
- benchmark/internal/command/xcode/benchmarks.go
- benchmark/internal/command/xcode/output.go
- benchmark/internal/command/xcode/output_test.go
- benchmark/internal/command/xcode/xcode.go
- benchmark/internal/executor/initializer.go
A more real-world alternative to `fio`.
> Benchmark: run XcodeBenchmark with different disk settings

- docs/faq.md
Resolves https://github.com/cirruslabs/softnet/issues/75.
> docs(FAQ): document unsupported DHCP client identifiers

- docs/orchard/architecture-and-security.md
- docs/orchard/deploying-controller.md
- docs/orchard/using-orchard-cli.md
- mkdocs.yml
* [Iterate over Orchard Architecture description](https://github.com/cirruslabs/tart/commit/66f1e693b9d81ab06e3067d33c2527e985d39307)
* [Document Orchard Controller customization (e.g. --listen-ssh)](https://github.com/cirruslabs/tart/commit/79c615a9c3b8cf8e43f8764f30bbdcb1c6287f7f)
* [New section: "Using Orchard CLI"](https://github.com/cirruslabs/tart/commit/a40077195e4dcae60a50eed758af84fefeb7d26f)
> Improve Orchard docs

- Sources/tart/Commands/Exec.swift
Also handle decrease the connection timeout to 1 second and provide a hint to the user.
> tart exec: explain that Tart Guest Agent is required

- .cirrus.yml
- Package.resolved
- Package.swift
- Sources/tart/Commands/IP.swift
- Sources/tart/MACAddressResolver/AgentResolver.swift
See https://github.com/cirruslabs/tart-guest-agent/pull/14.
> tart ip: implement --resolver=agent

- Sources/tart/Commands/Exec.swift
Resolves https://github.com/cirruslabs/tart/issues/1100.
> tart exec: handle input redirection of regular files
